### ISSUE TITLE
start-game.bat does not set username properly

### ISSUE THREAD

**Issue by Kawaiikat14** [Spiderlover/Toontown-2-Revised#2]
choosing a username on start-game.bat doesn't work. It always makes it dev which makes playing over hamachi not work (and yes I changed the localhost IP in the bat to my hamachi IP)

**Comment by Kawaiikat14** [comment]
boop

**Comment by MasterLoopyBM** [comment]
I don't know if that was the intended purpose or not (not a dev), but I for one want this fixed.

**Comment by Kawaiikat14** [comment]
Bumping again. Please fix

**Comment by Spiderlover** [comment]
@Kawaiikat14 interesting bug

**Comment by Spiderlover** [comment]
this is the intended purpose for now :(

**Comment by Kawaiikat14** [comment]
Will there ever be a fix?

**Comment by Spiderlover** [comment]
probably not, since I think the issue is with the Account Database, which is hard to figure out

**Comment by Kawaiikat14** [comment]
hmm. Odd
I Used a different launcher with some slight modifications
It works but it makes the game crash alot

**Comment by Spiderlover** [comment]
hmmmmm ok
